In [46]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [47]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import classification_report

# prep

Do a supersimple ML model with 3-4 variables

In [48]:
df=pd.read_csv(r"../data\Sleep_health_and_lifestyle_dataset.csv")
df

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,370,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
370,371,Female,59,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
371,372,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
372,373,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
373,374,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea

In [49]:
df["Sleep Disorder"].value_counts()

Sleep Disorder
Sleep Apnea    78
Insomnia       77
Name: count, dtype: int64

In [50]:
#only numeric
x=df.drop(columns=["Person ID", "Sleep Disorder", "Gender", "Occupation", "Blood Pressure", "BMI Category"])
y=~df["Sleep Disorder"].isna()

In [51]:
x

,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,Heart Rate,Daily Steps
0,27,6.1,6,42,6,77,4200
1,28,6.2,6,60,8,75,10000
2,28,6.2,6,60,8,75,10000
3,28,5.9,4,30,8,85,3000
4,28,5.9,4,30,8,85,3000
...,...,...,...,...,...,...,...
369,59,8.1,9,75,3,68,7000
370,59,8.0,9,75,3,68,7000
371,59,8.1,9,75,3,68,7000
372,59,8.1,9,75,3,68,7000
373,59,8.1,9,75,3,68,7000

In [52]:
x = x[["Age", "Sleep Duration"]]

In [53]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

# Train

In [54]:
models={
    "Linear Regression": LinearRegression(),
    "DecisionTreeRegressor":DecisionTreeRegressor(),
    "RandomForestRegressor":RandomForestRegressor(),
}

In [55]:
for model_name,model in models.items():
    print(f'Training {model_name}....')

    
    model.fit(x_train,y_train)

    y_pred=model.predict(x_test)
    y_pred= np.round(y_pred)
    
    print("Classification Report:\n", classification_report(y_test, y_pred))
    print("\n")

Training Linear Regression....
Classification Report:
               precision    recall  f1-score   support

       False       0.87      0.88      0.87        66
        True       0.83      0.81      0.82        47

    accuracy                           0.85       113
   macro avg       0.85      0.84      0.84       113
weighted avg       0.85      0.85      0.85       113



Training DecisionTreeRegressor....
Classification Report:
               precision    recall  f1-score   support

       False       0.91      0.92      0.92        66
        True       0.89      0.87      0.88        47

    accuracy                           0.90       113
   macro avg       0.90      0.90      0.90       113
weighted avg       0.90      0.90      0.90       113



Training RandomForestRegressor....
Classification Report:
               precision    recall  f1-score   support

       False       0.91      0.91      0.91        66
        True       0.87      0.87      0.87        47

    accuracy                           0.89       113
   macro avg       0.89      0.89      0.89       113
weighted avg       0.89      0.89      0.89       113

In [56]:
model.feature_importances_

array([0.49513226, 0.50486774])

In [ ]:
import joblib

# save it
joblib.dump(model, 'model.joblib')

['model.joblib']

In [58]:
#load

# Cargar
model_saved = joblib.load('model.joblib')

In [64]:
load_pred = model_saved.predict(pd.DataFrame([[60, 8.1]], columns=["Age", "Sleep Duration"]))
np.round(load_pred)

array([1.])